name: Go CI

on:
  pull_request:
    branches: [ main, gm-integ ]
  push:
    branches: [ main, gm-integ, 'feature/**' ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      
      - name: Go vet
        run: go vet ./...
      
      - name: Build
        run: go build ./...
      
      - name: Unit tests
        env:
          HL_TESTNET: "0"
        run: go test ./... -v -count=1 -short
